<a href="https://colab.research.google.com/github/MuNeNICK/Probability_Statics_1/blob/main/5430_0616.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
dice_data = np.array([1,2,3,4,5,6])

In [4]:
steps = 1000

In [5]:
dice_result = np.random.choice(dice_data, steps)

In [6]:
dice_result

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2, 6, 1,
       2, 5, 4, 1, 4, 6, 1, 3, 4, 1, 2, 4, 6, 4, 4, 1, 2, 2, 2, 1, 3, 5,
       4, 4, 3, 5, 3, 1, 1, 5, 6, 6, 1, 5, 2, 5, 2, 3, 3, 1, 2, 2, 2, 2,
       4, 4, 3, 4, 1, 4, 6, 5, 2, 3, 5, 4, 5, 5, 5, 4, 5, 5, 5, 1, 5, 4,
       3, 6, 6, 6, 1, 2, 6, 2, 4, 1, 6, 1, 2, 3, 5, 3, 1, 6, 4, 3, 3, 6,
       1, 6, 2, 1, 3, 3, 4, 3, 4, 3, 2, 3, 4, 4, 4, 3, 4, 5, 2, 3, 4, 2,
       3, 2, 5, 3, 4, 1, 4, 3, 4, 1, 1, 1, 4, 3, 4, 1, 5, 1, 6, 1, 6, 3,
       4, 3, 4, 6, 1, 1, 1, 4, 1, 3, 3, 1, 5, 4, 5, 6, 1, 5, 4, 6, 4, 5,
       6, 2, 6, 4, 1, 1, 1, 6, 6, 2, 1, 5, 2, 6, 6, 4, 2, 1, 1, 5, 4, 4,
       2, 6, 6, 1, 1, 2, 3, 1, 4, 6, 2, 2, 5, 1, 6, 1, 4, 3, 4, 3, 5, 4,
       6, 6, 4, 1, 4, 1, 5, 3, 4, 6, 6, 5, 1, 3, 4, 4, 2, 6, 4, 5, 6, 6,
       4, 4, 2, 2, 2, 4, 3, 3, 5, 4, 2, 3, 4, 6, 6, 6, 2, 5, 3, 3, 1, 2,
       6, 1, 5, 1, 4, 3, 6, 6, 1, 1, 6, 2, 2, 1, 4, 1, 4, 1, 5, 5, 1, 2,
       4, 5, 4, 3, 6, 2, 2, 3, 2, 6, 5, 6, 3, 6, 6,

In [7]:
dice_result[dice_result==1]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
len(dice_result[dice_result==1])

171

In [9]:
p1 = len(dice_result[dice_result==1]) / steps

In [10]:
print('1が出る確率:', p1)

1が出る確率: 0.171


In [11]:
p2 = len(dice_result[dice_result==2]) / steps
print('2が出る確率:', p2)

2が出る確率: 0.157


In [12]:
p3 = len(dice_result[dice_result==3]) / steps
print('3が出る確率:', p3)

3が出る確率: 0.157


In [13]:
p4 = len(dice_result[dice_result==4]) / steps
print('4が出る確率:', p4)

4が出る確率: 0.183


In [14]:
p5 = len(dice_result[dice_result==5]) / steps
print('5が出る確率:', p5)

5が出る確率: 0.161


In [15]:
p6 = len(dice_result[dice_result==6]) / steps
print('6が出る確率:', p6)

6が出る確率: 0.171


In [16]:
for i in range(1,7):
  p = len(dice_result[dice_result==i]) / steps
  print(i,'が出る確率:', p)

1 が出る確率: 0.171
2 が出る確率: 0.157
3 が出る確率: 0.157
4 が出る確率: 0.183
5 が出る確率: 0.161
6 が出る確率: 0.171


In [21]:
coin_data = np.array([0,1])

In [22]:
coin_result = np.random.choice(coin_data, steps)

In [24]:
coin_result

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,

In [27]:
p0 = len(coin_result[coin_result==0]) / steps
print('表が出る確率:', p0)
p1 = len(coin_result[coin_result==1]) / steps
print('表が出る確率:', p1)

表が出る確率: 0.468
表が出る確率: 0.532


In [30]:
for i in range(0,2):
  p = len(coin_result[coin_result==i]) / steps
  if(i==0):
    print('表が出る確率:', p)
  if(i==1):
    print('裏が出る確率:', p)

表が出る確率: 0.468
裏が出る確率: 0.532
